import { config } from '../../config.js';
import { Pdf } from '../../lib/pdf.js';
import { formatMoney } from '../../lib/money.js';
import { getInvoice } from './service.js';
import { getSubscriber } from '../subscribers/service.js';
import * as storage from '../storage/service.js';

function storageKey(number: string): string {
  return `invoices/${number}.pdf`;
}

/** Render a branded invoice PDF. */
async function render(invoiceId: string): Promise<{ buffer: Buffer; key: string; number: string }> {
  const invoice = await getInvoice(invoiceId);
  const subscriber = await getSubscriber(invoice.subscriber_id);
  const cur = invoice.currency;

  const pdf = new Pdf();
  let y = 800;
  pdf.text(50, y, 20, config.brandName, true);
  pdf.text(420, y, 12, 'TAX INVOICE', true);
  y -= 18;
  pdf.text(420, y, 10, `No: ${invoice.number}`);
  y -= 14;
  pdf.text(420, y, 10, `Issued: ${new Date(invoice.issued_at).toISOString().slice(0, 10)}`);
  y -= 14;
  pdf.text(420, y, 10, `Due: ${new Date(invoice.due_date).toISOString().slice(0, 10)}`);

  y = 740;
  pdf.text(50, y, 11, 'Bill to:', true);
  y -= 15;
  pdf.text(50, y, 11, subscriber.full_name);
  y -= 14;
  pdf.text(50, y, 10, subscriber.phone + (subscriber.email ? ` · ${subscriber.email}` : ''));
  y -= 14;
  pdf.text(50, y, 10, `Status: ${invoice.status.toUpperCase()}`);

  // Line-item table
  y = 670;
  pdf.rule(y + 12);
  pdf.text(50, y, 10, 'Description', true);
  pdf.text(360, y, 10, 'Qty', true);
  pdf.text(420, y, 10, 'Unit', true);
  pdf.text(500, y, 10, 'Amount', true);
  pdf.rule(y - 6);
  y -= 22;

  for (const item of invoice.items) {
    pdf.text(50, y, 10, String(item.description).slice(0, 50));
    pdf.text(360, y, 10, String(item.quantity));
    pdf.text(420, y, 10, formatMoney(Number(item.unit_price_cents), cur));
    pdf.text(500, y, 10, formatMoney(Number(item.amount_cents), cur));
    y -= 18;
  }

  y -= 6;
  pdf.rule(y + 10);
  pdf.text(420, y, 10, 'Subtotal');
  pdf.text(500, y, 10, formatMoney(invoice.subtotal_cents, cur));
  y -= 16;
  pdf.text(420, y, 10, 'Tax (VAT)');
  pdf.text(500, y, 10, formatMoney(invoice.tax_cents, cur));
  y -= 18;
  pdf.text(420, y, 12, 'Total', true);
  pdf.text(500, y, 12, formatMoney(invoice.total_cents, cur), true);

  pdf.text(50, 60, 9, `Generated by ${config.brandName} billing · ${new Date().toISOString()}`);

  return { buffer: pdf.build(), key: storageKey(invoice.number), number: invoice.number };
}

/**
 * Get the invoice PDF, generating and persisting it to object storage on first
 * request (then served from storage thereafter).
 */
export async function getInvoicePdf(invoiceId: string): Promise<{ buffer: Buffer; filename: string }> {
  const invoice = await getInvoice(invoiceId);
  const key = storageKey(invoice.number);

  if (await storage.exists(key)) {
    return { buffer: await storage.get(key), filename: `${invoice.number}.pdf` };
  }
  const { buffer } = await render(invoiceId);
  await storage.put(key, buffer);
  return { buffer, filename: `${invoice.number}.pdf` };
}
